      - name: Restore dependencies
        run: dotnet restore "JSEmu Launcher/H1Emu Launcher.csproj" --runtime win-x64

      - name: Publish launcher
        run: >
          dotnet publish
          "JSEmu Launcher/H1Emu Launcher.csproj"
          --configuration Release
          --runtime win-x64
          --self-contained true
          --no-restore
          --output "publish/JSEmu-Launcher-win-x64"
          -p:PublishSingleFile=false
          -p:DebugType=None
          -p:DebugSymbols=false